baseURL = 'https://sneaky-potato.github.io/'
languageCode = 'en-us'
title = 'Potato'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[menu]
  [[menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="blog"
    name = 'Blog'
    url = '/blog/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30
  [[menu.main]]
    pageRef="/cv.pdf"
    name = 'CV'
    url = '/cv.pdf'
    weight = 30

[params]
  sitename = "Awesome hugo blog"
  defaultColor = "light" # set color mode: dark, light, auto
  description = "Th√®me minimal pour blog Hugo avec prise en charge des modes clair et sombre"
  mainSections = ['blog']
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  math = true


[params.author]
  avatar = "chasma.jpeg" # put the file in assets folder; also ensure that image has same height and width
  intro = "Ashwani Kumar Kamal"
  name = "Ashwani Kumar Kamal"
  description = ""

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/sneaky-potato"
